name: Auto Build and Release

on:
  push:
    branches:
      - dev

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build hexo
        run: npm run build

      - name: Zip the built hexo
        run: |
          cd public
          zip -r dist.zip dist

      - name: Upload artifact
        uses: actions/upload-artifact@master
        if: ${{ !github.head_ref }}
        with:
          name: ${{ matrix.goos }}_${{ matrix.goarch }}
          path: /public/dist.zip